name: flutter_clean_architecture
description: A Flutter package that implements the Clean Architecture by Uncle Bob in Flutter. It provides Views, Controllers, Presenters, Observers, and UseCases.
version: 5.0.2
homepage: https://github.com/ShadyBoukhary/flutter_clean_architecture

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  meta: ^1.8.0
  provider: ^6.1.5+1
  responsive_builder: ^0.7.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.1
  pedantic: ^1.11.0
